### PR TITLE
Staging Updates to Python Code from Aerospace Corp.

### PR DESCRIPTION
**Pull request by bhilburn**
This PR stages #106 and #116 onto `SigMF/master`.

I am staging these here because they are both rather large changesets, and the latter builds on the former, so I don't think it makes sense to evaluate #106 on its own at this point - especially since it was filed over a year ago.

@Teque5 - I confirmed that this staging branch correctly has your two changesets by `diff`ing it against `aerospace/public/release`. The only difference is that you originally branched before I merged `CODE_OF_CONDUCT.md` into `master` (see 336fcec398b), and you haven't pulled since then.

Update: have now also cherry-picked #115 to this branch.

Closes #106, #116, #115.

### CODE REVIEW

**Comment by bhilburn** [comment]
Okay, I just cherry-picked @nathan-turner111's commit from #115 over to this branch. PR #115 and #116 shared a common history in changeset but not commits, so merging them both would have turned into a merge conflict nightmare.

@nathan-turner111 @Teque5  - This PR should now include all 3 PRs that you've filed, and merging this branch will close all three. Focusing review / edits here to organize the effort.

**Comment by bhilburn** [comment]
By the way, now that I've slept, #115 would have been fine, hah. Still planning to test it on top of #106 and #116 since I'm guessing that's how its being used at Aerospace. If that causes issues, we can split it back out, and then rebase it once #106 and #116 are merged 🙂

**Comment by bhilburn** [comment]
@Teque5, @nathan-turner111 - If you're able, it would be *super* helpful if you could pull this staged branch and test it to make sure it works as you expect as compared to your fork. Assuming it does, we should be good. If not, we just need to resolve the discrepancies.

Tagging @dkozel, as well, as I know he has an interest in getting this done too.

**Comment by bhilburn** [comment]
Just a ping on this, @Teque5! Any chance your team can give this branch a go? I believe it should be exactly what you are using in the branch on your fork.

**Comment by nathan-turner111** [comment]
@bhilburn - I just pulled the branch and ran the GUI. It works as expected for me. However after some testing I realized I was not able to get the GUI running with python 3.6, so at least python 3.7 will be required to use it for now. I also noticed that the newest version of numpy requires python 3.5, but the project is classified under many versions of python below 3.5. I can't speak for @Teque5 commits.

**Comment by Teque5** [comment]
I will take a look at this in a few hours.

**Comment by Teque5** [comment]
So all the code from our PR looks fine and works with what we have. The GUI works just fine with python 3.6.9 on my Ubuntu 18.04 machine in a virtualenv. But I do have some notes:

- Perhaps this should be in a `scripts/` folder that has a link to it through the `setup.py` as either a `script` or `entry_point`. It seems odd that it's in the root.
- I think little endian should be default. it's currently set to big-endian.
- I can't figure out how to load a sigmf file. It seems I can load an archive, but not a pair of `.sigmf-data` and `.sigmf-meta` files.
- I'm not sure I see the point of the GUI. If I started with only a data file and wanted to create an archive this would be useful but I usually start with the `gr-sigmf` output and already have metadata.
- I ran it with `python3 sigmf_gui.py`, but you should really just add `#!/usr/bin/env python3` and set it as executable.

**Comment by bhilburn** [comment]
#106 and #116 are now merged. Going to move comments from here regarding the GUI over to #115

**Pull request closed without merging**
