### PR TITLE
Clarify usage of core:offset

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Comment by bhilburn** [comment]
Thanks, @mbr0wn.

Pinging @smunaut for a review, as well. This is obviously a really simple change, but especially with the discussion in #10 I want to make sure we all agree on how we talk about sample indices in the spec :)

**Comment by smunaut** [comment]
The usage I saw for this fields where, as indicated in the commit, when you have a recording split over several files or when you have time synced captures at the same sample rate to indicate the time offset between them.

But that can also be used when splitting / slicing capture data to avoid having to rewrite all the offsets in the file.

All in all it's a general purpose field you can use however you'd like. Readers should just apply the offset.

The only thing I would change is :
* The field should be int64 not uint64
* All sample index should actually be int64 and always fit inside int64 when the offset is applied (so that readers don't have to handle INT64_MAX + INT64_MAX cases)

**Comment by bhilburn** [comment]
Comment from @kpreid:

> That seems reasonable. I feel like there's some clarification that ought to be made (along the lines of "applications should not assume that core:offset means anything in particular other than how sample indexes should be displayed/accepted for reference by users" but more objectively defined) but I can't think of it at the moment.

**Comment by bhilburn** [comment]
Thanks so much for the quick fix, @mbr0wn! =)

**Pull request merged**
