### PR TITLE
use SigMFArchiveReader for fromfile()

### LINKED ISSUE #244: SigMF archive error reading data file
I think that there is an error opening sigmf archive files. The compliant dataset file is no recognized as a valid file because the relative path of the tar member is used https://github.com/gnuradio/SigMF/blob/1eef44a67636ab15078e7eecc00144b9e18cdaa3/sigmf/sigmffile.py#L779

### PR DESCRIPTION
**Pull request by jacobagilbert**
Closes #244

Also cleans up SigMFFileError imports/usage.

### CODE REVIEW

**Comment by jacobagilbert** [comment]
@gmabey does this seem like a reasonable way to address 244? I think we have accumulated a bit of architectural debt in the python module and it we can discuss that in the future (there is a circular import issue here which is why the import is inline) but that can be done once we get a functional release up.

**Comment by gmabey** [comment]
Yes, looks very reasonable to me, although I have not yet actually tried it.  And -- I appreciate those cleanups too.

**Comment by gmabey** [comment]
I'm getting a `Metadata in archive did not .validate()!` that I didn't expect, but there's no detail.  It looks like @jacobagilbert had that part commented out in #263.

Actually I've had that error pop up for a while, I just kept hoping it would go away when those validate PRs were finally merged.  Is anyone else seeing that message?

**Comment by jacobagilbert** [comment]
Ah yea i should probably add that. `validate()` no longer returns a bool, it throws an exception if it fails. Thats a bug.

**Comment by jacobagilbert** [comment]
Concurrence on the call today, merging.

**Pull request merged**
